### PR TITLE
Update to 1.19.2

### PR DESCRIPTION
**Pull request by Martijnpold**
Update mod to function on 1.19.2

Some small notes:
- Redstone link might have some issues. Handlers and signals appear to be registered correctly, but Create redstone links do not appear to activate. I'm guessing it's one of the following:
     - Frequency no longer equal due to the changes required for retrieving items from registries. `ItemStack#getRegistryName` no longer exists so that needed some changing.
     - Create made internal changes to its API
     - My computercraft program is just wrong in some way.
     - Note: I'm putting this PR here anyway, could be worth testing with existing setups to see if maybe I just messed up my CC code.
- Added some gradle options to more easily update create, flywheel and registrate.
- Left the jade dependency as-is, it doesn't appear to be used in any way but I could be wrong about that.

### CODE REVIEW

**Comment by Sascha-T** [comment]
redstone links were whacky in the first place, ill have to revisit this entire mod sometime, merged

**Comment by Merith-TK** [comment]
My boi Martijn, 

Create is NOT on 1.19.2 yet man,

**Comment by Sascha-T** [comment]
ive been fooled and quite possibly bamboozled

**Comment by Sascha-T** [comment]
no i havent, it quite literally **built**

i think this mod just needs a complete refashion/rewrite

**Comment by Merith-TK** [comment]
Yeah the mod builds, but there is no 1.19.2 create yet so there was no way it should've built lol

**Comment by Martijnpold** [comment]
@Merith-TK Create is open source and has already had a working 1.19 branch for a while. There was a 1.19.2 create, it just wasn't publicly released yet, so if you wanted to use it you had to build it yourself. It released just now though 👍.

They even had the 1.19.2 version up on their maven repo, which should be proof that the version does actually exist, otherwise as @Sascha-T mentioned it wouldn't even build.

**Comment by Merith-TK** [comment]
Still, wish this project remained on 1.18.2 (at least as an branch) and got
patched for 0.5.0d so I can actually try the damned thing, the current
"release" will not start on 1.18.2 which means I physically cannot test if
it is suitable to what I would actually require since CC Bridge is
literally just an Display Link,

**Comment by Martijnpold** [comment]
@Merith-TK  I did originally expect Sacha to make a 1.18 branch prior to merging this, but he can still do that retroactively. Anyway, you can still checkout prior to this commit yourself, and get that version, that's the wonders of git ;)

**Comment by Martijnpold** [comment]
If you want to get the prior version a pretty recent one is still up on curseforge (https://www.curseforge.com/minecraft/mc-mods/create-computing). There is, as far as I can tell, only one commit missing, which is [this one](https://github.com/Sascha-T/create-computing/commit/2d8c37510ca5e866446d1bb9ffbb95b3cae29320), and adds getTrainName and getStopName.

**Pull request merged**
